# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [3]:
url= "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep= "\t" )
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Assign it to a variable called chipo.

### Step 4. What is the name of the max valued product?

In [4]:
chipo = chipo.sort_values("item_price", ascending=False)
chipo

,order_id,quantity,item_name,choice_description,item_price
2624,1042,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Sour Cream,...",$9.39
4419,1762,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$9.39
4036,1615,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$9.39
1825,738,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$9.39
3115,1243,1,Carnitas Salad Bowl,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",$9.39
...,...,...,...,...,...
3145,1254,1,Canned Soda,[Diet Dr. Pepper],$1.09
414,180,1,Canned Soda,[Dr. Pepper],$1.09
3162,1262,1,Canned Soda,[Coca Cola],$1.09
821,338,1,Canned Soda,[Coca Cola],$1.09
1457,591,1,Canned Soda,[Sprite],$1.09

In [5]:
to_string_dollar = lambda x: str("$"+ str(x))
chipo.itme_price = chipo.item_price.apply(to_string_dollar)
chipo

,order_id,quantity,item_name,choice_description,item_price
2624,1042,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Sour Cream,...",$9.39
4419,1762,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$9.39
4036,1615,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$9.39
1825,738,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$9.39
3115,1243,1,Carnitas Salad Bowl,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",$9.39
...,...,...,...,...,...
3145,1254,1,Canned Soda,[Diet Dr. Pepper],$1.09
414,180,1,Canned Soda,[Dr. Pepper],$1.09
3162,1262,1,Canned Soda,[Coca Cola],$1.09
821,338,1,Canned Soda,[Coca Cola],$1.09
1457,591,1,Canned Soda,[Sprite],$1.09

In [6]:
 chipo.item_price = chipo.item_price.str[1:].astype(float)
 chipo

,order_id,quantity,item_name,choice_description,item_price
2624,1042,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Sour Cream,...",9.39
4419,1762,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",9.39
4036,1615,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",9.39
1825,738,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",9.39
3115,1243,1,Carnitas Salad Bowl,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",9.39
...,...,...,...,...,...
3145,1254,1,Canned Soda,[Diet Dr. Pepper],1.09
414,180,1,Canned Soda,[Dr. Pepper],1.09
3162,1262,1,Canned Soda,[Coca Cola],1.09
821,338,1,Canned Soda,[Coca Cola],1.09
1457,591,1,Canned Soda,[Sprite],1.09

In [7]:
max(chipo.item_price)#el precio maximo

44.25

In [8]:
index = chipo.item_price.idxmax()
print(index)
#cual es el indice del precio maximo

3598

In [13]:
 x = chipo.item_price[chipo.item_price == max(chipo.item_price)]
 x
 # mascara a la columna de itme_price y le decimos que devuelva todos los item_price cuando el item_price sea el maximo. nos da una serie (porque estoy "llamando a la columna") con el indice y el valor.

3598    44.25
Name: item_price, dtype: float64

In [14]:
#ejemplo de mascara: quiero que me devuelva todos los item_names en que el precio sea 8.75

s= chipo.item_name[chipo.item_price == 8.75]
s

2240          Chicken Bowl
2172          Chicken Bowl
2200       Chicken Burrito
2171       Chicken Burrito
2212       Chicken Burrito
               ...
693     Chicken Salad Bowl
289        Chicken Burrito
372        Chicken Burrito
486        Chicken Burrito
487        Chicken Burrito
Name: item_name, Length: 730, dtype: object

In [15]:
s = chipo[chipo.item_price == max(chipo.item_price)]
s
#aqui me devolve el datframe porque no estoy llamando a la

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

In [19]:
#queremos saber cuanto cuesta (el precio real) de cada producto. creamos una columna que guarde el precio por unidad.

chipo[chipo.item_name == "Chicken Bowl"]

,order_id,quantity,item_name,choice_description,item_price
2240,903,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice]]",8.75
2172,877,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Lettu...",8.75
2173,877,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...",8.75
2163,873,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]",8.75
2264,912,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
...,...,...,...,...,...
892,369,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Fajita Vegg...",10.98
1719,693,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",10.98
1966,794,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",10.98
3672,1470,1,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...",10.98
2919,1160,1,Chicken Bowl,"[Fresh Tomato (Mild), [Guacamole, Rice]]",10.58

In [21]:
#creamos nueva columna por precio unidad.

chipo["unity_price"]= chipo.item_price / chipo.quantity
chipo

,order_id,quantity,item_name,choice_description,item_price,unity_price
2624,1042,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Sour Cream,...",9.39,9.39
4419,1762,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",9.39,9.39
4036,1615,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",9.39,9.39
1825,738,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",9.39,9.39
3115,1243,1,Carnitas Salad Bowl,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",9.39,9.39
...,...,...,...,...,...,...
3145,1254,1,Canned Soda,[Diet Dr. Pepper],1.09,1.09
414,180,1,Canned Soda,[Dr. Pepper],1.09,1.09
3162,1262,1,Canned Soda,[Coca Cola],1.09,1.09
821,338,1,Canned Soda,[Coca Cola],1.09,1.09
1457,591,1,Canned Soda,[Sprite],1.09,1.09

In [29]:
chipo= chipo.sort_index()
chipo

,order_id,quantity,item_name,choice_description,item_price,unity_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

In [30]:
chipo_description= chipo.groupby("choice_description").max()
chipo_description

,order_id,quantity,item_name,item_price,unity_price
choice_description,,,,,
"[Adobo-Marinated and Grilled Chicken, Pinto Beans, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",214,1,Burrito,7.40,7.40
"[Adobo-Marinated and Grilled Chicken, [Sour Cream, Cheese, Cilantro-Lime Rice]]",279,1,Burrito,7.40,7.40
[Adobo-Marinated and Grilled Chicken],217,1,Crispy Tacos,7.40,7.40
"[Adobo-Marinated and Grilled Steak, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",279,1,Bowl,7.40,7.40
[Adobo-Marinated and Grilled Steak],217,1,Crispy Tacos,7.40,7.40
...,...,...,...,...,...
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Black Beans, Cheese, Lettuce]]",1309,1,Chicken Burrito,8.49,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Black Beans, Lettuce]]",1215,1,Chicken Bowl,8.49,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Cheese, Lettuce]]",51,1,Chicken Burrito,8.49,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Fajita Veggies, Cheese, Sour Cream, Lettuce]]",51,1,Barbacoa Bowl,8.99,8.99
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Fajita Veggies, Lettuce]]",1299,1,Barbacoa Bowl,8.99,8.99

In [33]:
chipo_description.sort_values("unity_price", ascending=False)

,order_id,quantity,item_name,item_price,unity_price
choice_description,,,,,
"[Tomatillo Green Chili Salsa, [Black Beans, Cheese, Guacamole]]",1692,2,Chicken Salad Bowl,22.50,11.89
"[Roasted Chili Corn Salsa, [Fajita Vegetables, Rice, Cheese, Guacamole, Lettuce]]",1403,1,Steak Salad Bowl,11.89,11.89
"[Roasted Chili Corn Salsa, [Rice, Cheese, Lettuce, Guacamole]]",1106,1,Steak Salad Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Pinto Beans, Cheese, Guacamole, Lettuce]]",250,1,Steak Salad Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Rice, Fajita Vegetables, Sour Cream, Cheese, Lettuce, Guacamole]]",478,1,Steak Salad Bowl,11.89,11.89
...,...,...,...,...,...
[Peach Orange],1632,2,Nantucket Nectar,6.78,3.39
[Mountain Dew],1562,2,Canned Soda,2.18,1.09
[Diet Dr. Pepper],1578,2,Canned Soda,2.18,1.09
[Coca Cola],1475,2,Canned Soda,2.18,1.09
[Dr. Pepper],1575,2,Canned Soda,2.18,1.09

In [35]:
chipo_description[chipo_description.unity_price == max(chipo_description.unity_price)]

,order_id,quantity,item_name,item_price,unity_price
choice_description,,,,,
"[Fresh Tomato Salsa, Guacamole]",1483,1,Steak Soft Tacos,11.89,11.89
"[Fresh Tomato Salsa, [Black Beans, Cheese, Guacamole, Lettuce]]",1296,1,Steak Salad Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Cheese, Guacamole, Lettuce]]",1790,1,Steak Salad Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Fajita Vegetables, Black Beans, Cheese, Sour Cream, Guacamole]]",1768,1,Steak Salad Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Fajita Vegetables, Guacamole]]",1189,1,Steak Salad Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole, Lettuce]]",1748,1,Veggie Salad Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Sour Cream, Guacamole]]",1443,3,Veggie Burrito,33.75,11.89
"[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Cheese, Sour Cream, Guacamole, Lettuce]]",1780,1,Veggie Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Fajita Vegetables, Sour Cream, Cheese, Lettuce, Guacamole]]",1718,2,Steak Salad Bowl,23.50,11.89
"[Fresh Tomato Salsa, [Pinto Beans, Cheese, Guacamole, Lettuce]]",250,1,Steak Salad Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Guacamole]]",1386,1,Steak Salad Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Rice, Fajita Vegetables, Pinto Beans, Black Beans, Sour Cream, Cheese, Lettuce, Guacamole]]",501,1,Barbacoa Salad Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Rice, Fajita Vegetables, Sour Cream, Cheese, Lettuce, Guacamole]]",478,1,Steak Salad Bowl,11.89,11.89
"[Fresh Tomato Salsa, [Rice, Pinto Beans, Cheese, Sour Cream, Guacamole, Lettuce]]",1786,1,Steak Salad Bowl,11.89,11.89
"[Roasted Chili Corn Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Sour Cream, Guacamole, Lettuce]]",1526,3,Veggie Burrito,35.25,11.89
"[Roasted Chili Corn Salsa, [Fajita Vegetables, Rice, Black Beans, Guacamole]]",1720,1,Veggie Bowl,11.89,11.89
"[Roasted Chili Corn Salsa, [Fajita Vegetables, Rice, Cheese, Guacamole, Lettuce]]",1403,1,Steak Salad Bowl,11.89,11.89
"[Roasted Chili Corn Salsa, [Fajita Vegetables, Rice, Pinto Beans, Cheese, Sour Cream, Guacamole, Lettuce]]",1499,1,Steak Salad Bowl,11.89,11.89
"[Roasted Chili Corn Salsa, [Rice, Cheese, Lettuce, Guacamole]]",1106,1,Steak Salad Bowl,11.89,11.89
"[Tomatillo Green Chili Salsa, [Black Beans, Cheese, Guacamole]]",1692,2,Chicken Salad Bowl,22.50,11.89
"[Tomatillo Green Chili Salsa, [Rice, Fajita Vegetables, Pinto Beans, Sour Cream, Cheese, Lettuce, Guacamole]]",970,1,Veggie Burrito,11.89,11.89
"[Tomatillo Red Chili Salsa, [Black Beans, Cheese, Guacamole]]",123,2,Veggie Burrito,23.78,11.89
"[Tomatillo Red Chili Salsa, [Black Beans, Cheese, Sour Cream, Guacamole]]",1283,1,Carnitas Burrito,11.89,11.89
"[Tomatillo Red Chili Salsa, [Fajita Vegetables, Black Beans, Cheese, Guacamole, Lettuce]]",1223,2,Veggie Bowl,23.78,11.89
"[Tomatillo Red Chili Salsa, [Rice, Black Beans, Cheese, Sour Cream, Guacamole, Lettuce]]",1736,1,Veggie Bowl,11.89,11.89

In [36]:
chipo_description = chipo.groupby(["choice_description", "item_name"]).max()
chipo_description

,,order_id,quantity,item_price,unity_price
choice_description,item_name,,,,
"[Adobo-Marinated and Grilled Chicken, Pinto Beans, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",Burrito,214,1,7.40,7.40
"[Adobo-Marinated and Grilled Chicken, [Sour Cream, Cheese, Cilantro-Lime Rice]]",Burrito,279,1,7.40,7.40
[Adobo-Marinated and Grilled Chicken],Crispy Tacos,217,1,7.40,7.40
"[Adobo-Marinated and Grilled Steak, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]",Bowl,279,1,7.40,7.40
[Adobo-Marinated and Grilled Steak],Crispy Tacos,217,1,7.40,7.40
...,...,...,...,...,...
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Black Beans, Cheese, Lettuce]]",Chicken Burrito,1267,1,8.49,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Black Beans, Lettuce]]",Chicken Bowl,1215,1,8.49,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Cheese, Lettuce]]",Chicken Burrito,51,1,8.49,8.49
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Fajita Veggies, Cheese, Sour Cream, Lettuce]]",Barbacoa Bowl,51,1,8.99,8.99
"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Green Chili Salsa (Medium)], [Rice, Pinto Beans, Fajita Veggies, Lettuce]]",Barbacoa Bowl,1299,1,8.99,8.99

In [38]:
chipo_grouped = chipo.groupby("item_name").max()
chipo_grouped

,order_id,quantity,choice_description,item_price,unity_price
item_name,,,,,
6 Pack Soft Drink,1803,2,[Sprite],12.98,6.49
Barbacoa Bowl,1825,1,"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...",11.75,11.75
Barbacoa Burrito,1827,1,"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomat...",11.75,11.75
Barbacoa Crispy Tacos,1330,2,"[[Roasted Chili Corn Salsa (Medium), Tomatillo...",18.50,11.75
Barbacoa Salad Bowl,1751,1,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",11.89,11.89
Barbacoa Soft Tacos,1703,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",11.75,11.75
Bottled Water,1831,10,NaN,15.00,1.50
Bowl,279,3,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",22.20,7.40
Burrito,313,1,"[White Rice, Adobo-Marinated and Grilled Steak...",7.40,7.40
Canned Soda,1621,4,[Sprite],4.36,1.09
Canned Soft Drink,1829,4,[Sprite],5.00,1.25
Carnitas Bowl,1831,3,"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomat...",35.25,11.75
Carnitas Burrito,1821,2,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",18.50,11.75
Carnitas Crispy Tacos,1774,2,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",17.98,11.75
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.99,8.99
Carnitas Salad Bowl,1692,1,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",11.89,11.89
Carnitas Soft Tacos,1811,1,"[Tomatillo-Red Chili Salsa (Hot), [Cheese, Sou...",11.75,11.75
Chicken Bowl,1828,3,"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...",32.94,11.25
Chicken Burrito,1817,4,"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...",35.00,11.25
Chicken Crispy Tacos,1775,2,"[Tomatillo-Green Chili Salsa (Medium), [Black ...",17.50,11.25
Chicken Salad,1598,1,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",10.98,10.98
Chicken Salad Bowl,1834,2,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",22.50,11.25
Chicken Soft Tacos,1832,2,"[[Tomatillo-Red Chili Salsa (Hot), Roasted Chi...",21.96,11.25
Chips,1831,3,NaN,6.45,2.15
Chips and Fresh Tomato Salsa,1790,15,NaN,44.25,2.95
Chips and Guacamole,1832,4,NaN,17.80,4.45
Chips and Mild Fresh Tomato Salsa,279,1,NaN,3.00,3.00
Chips and Roasted Chili Corn Salsa,1513,2,NaN,5.90,2.95
Chips and Roasted Chili-Corn Salsa,1565,1,NaN,2.39,2.39
Chips and Tomatillo Green Chili Salsa,1787,2,NaN,5.90,2.95
Chips and Tomatillo Red Chili Salsa,1779,2,NaN,5.90,2.95
Chips and Tomatillo-Green Chili Salsa,1604,2,NaN,4.78,2.39
Chips and Tomatillo-Red Chili Salsa,1637,3,NaN,7.17,2.39
Crispy Tacos,217,1,[Adobo-Marinated and Grilled Steak],7.40,7.40
Izze,1468,1,[Grapefruit],3.39,3.39
Nantucket Nectar,1632,2,[Pomegranate Cherry],6.78,3.39
Salad,575,1,"[White Rice, Adobo-Marinated and Grilled Chick...",7.40,7.40
Side of Chips,1629,8,NaN,13.52,1.69
Steak Bowl,1796,3,"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomat...",26.07,11.75
Steak Burrito,1833,3,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",27.75,11.75
Steak Crispy Tacos,1810,2,"[[Roasted Chili Corn Salsa (Medium), Tomatillo...",17.98,11.75
Steak Salad,1406,1,"[[Lettuce, Fajita Veggies]]",8.99,8.99
Steak Salad Bowl,1818,2,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",23.78,11.89
Steak Soft Tacos,1808,2,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",18.50,11.75
Veggie Bowl,1780,2,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",16.98,11.25
Veggie Burrito,1830,3,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",33.75,11.25
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49
Veggie Salad,1635,1,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.49,8.49
Veggie Salad Bowl,1818,1,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
Veggie Soft Tacos,1559,2,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",16.98,11.25

In [39]:
max(chipo_grouped.unity_price)

11.89

In [40]:
chipo_grouped[chipo_grouped.unity_price == max(chipo_grouped.unity_price)]
chipo_grouped

,order_id,quantity,choice_description,item_price,unity_price
item_name,,,,,
6 Pack Soft Drink,1803,2,[Sprite],12.98,6.49
Barbacoa Bowl,1825,1,"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...",11.75,11.75
Barbacoa Burrito,1827,1,"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomat...",11.75,11.75
Barbacoa Crispy Tacos,1330,2,"[[Roasted Chili Corn Salsa (Medium), Tomatillo...",18.50,11.75
Barbacoa Salad Bowl,1751,1,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",11.89,11.89
Barbacoa Soft Tacos,1703,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",11.75,11.75
Bottled Water,1831,10,NaN,15.00,1.50
Bowl,279,3,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",22.20,7.40
Burrito,313,1,"[White Rice, Adobo-Marinated and Grilled Steak...",7.40,7.40
Canned Soda,1621,4,[Sprite],4.36,1.09
Canned Soft Drink,1829,4,[Sprite],5.00,1.25
Carnitas Bowl,1831,3,"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomat...",35.25,11.75
Carnitas Burrito,1821,2,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",18.50,11.75
Carnitas Crispy Tacos,1774,2,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",17.98,11.75
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.99,8.99
Carnitas Salad Bowl,1692,1,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",11.89,11.89
Carnitas Soft Tacos,1811,1,"[Tomatillo-Red Chili Salsa (Hot), [Cheese, Sou...",11.75,11.75
Chicken Bowl,1828,3,"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...",32.94,11.25
Chicken Burrito,1817,4,"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...",35.00,11.25
Chicken Crispy Tacos,1775,2,"[Tomatillo-Green Chili Salsa (Medium), [Black ...",17.50,11.25
Chicken Salad,1598,1,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",10.98,10.98
Chicken Salad Bowl,1834,2,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",22.50,11.25
Chicken Soft Tacos,1832,2,"[[Tomatillo-Red Chili Salsa (Hot), Roasted Chi...",21.96,11.25
Chips,1831,3,NaN,6.45,2.15
Chips and Fresh Tomato Salsa,1790,15,NaN,44.25,2.95
Chips and Guacamole,1832,4,NaN,17.80,4.45
Chips and Mild Fresh Tomato Salsa,279,1,NaN,3.00,3.00
Chips and Roasted Chili Corn Salsa,1513,2,NaN,5.90,2.95
Chips and Roasted Chili-Corn Salsa,1565,1,NaN,2.39,2.39
Chips and Tomatillo Green Chili Salsa,1787,2,NaN,5.90,2.95
Chips and Tomatillo Red Chili Salsa,1779,2,NaN,5.90,2.95
Chips and Tomatillo-Green Chili Salsa,1604,2,NaN,4.78,2.39
Chips and Tomatillo-Red Chili Salsa,1637,3,NaN,7.17,2.39
Crispy Tacos,217,1,[Adobo-Marinated and Grilled Steak],7.40,7.40
Izze,1468,1,[Grapefruit],3.39,3.39
Nantucket Nectar,1632,2,[Pomegranate Cherry],6.78,3.39
Salad,575,1,"[White Rice, Adobo-Marinated and Grilled Chick...",7.40,7.40
Side of Chips,1629,8,NaN,13.52,1.69
Steak Bowl,1796,3,"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomat...",26.07,11.75
Steak Burrito,1833,3,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",27.75,11.75
Steak Crispy Tacos,1810,2,"[[Roasted Chili Corn Salsa (Medium), Tomatillo...",17.98,11.75
Steak Salad,1406,1,"[[Lettuce, Fajita Veggies]]",8.99,8.99
Steak Salad Bowl,1818,2,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",23.78,11.89
Steak Soft Tacos,1808,2,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",18.50,11.75
Veggie Bowl,1780,2,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",16.98,11.25
Veggie Burrito,1830,3,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",33.75,11.25
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49
Veggie Salad,1635,1,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.49,8.49
Veggie Salad Bowl,1818,1,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
Veggie Soft Tacos,1559,2,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",16.98,11.25

In [41]:
k = chipo.groupby("item_name").max()
k[k.unity_price == max(k.unity_price)]

,order_id,quantity,choice_description,item_price,unity_price
item_name,,,,,
Barbacoa Salad Bowl,1751,1,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",11.89,11.89
Carnitas Salad Bowl,1692,1,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",11.89,11.89
Steak Salad Bowl,1818,2,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",23.78,11.89

In [42]:
# cuantos priductos han costado mas que 10.00$

products = chipo.item_name[(chipo.item_price >10.0)]
products.nunique()

31

In [44]:
(chipo.item_price >10.0).any()#si hay alguno que cumple la condiciÃ³n

True

In [45]:
#si todos cumplen la condiciÃ³n
(chipo.item_price >10.0).all()

False

In [46]:
c = chipo.item_price >10.0
c.values

array([False, False, False, ...,  True, False, False])

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [50]:
chipo.iloc[:, 2:5:2]

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

In [10]:
# delete the duplicates in item_name and quantity


# select only the products with quantity equals to 1


# select only the item_name and item_price columns


# sort the values from the most to less expensive

In [51]:
# delete the duplicates in item_name and quantity

chipo.dropped = chipo.copy()
chipo_dropped= chipo.dropped.drop_duplicates(["item_name", "quantity"])
chipo_dropped

,order_id,quantity,item_name,choice_description,item_price,unity_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
...,...,...,...,...,...,...
3890,1559,2,Carnitas Crispy Tacos,"[Fresh Tomato Salsa (Mild), [Cheese, Lettuce]]",17.98,8.99
3973,1592,4,Canned Soft Drink,[Coke],5.00,1.25
4152,1660,10,Bottled Water,NaN,15.00,1.50
4354,1738,2,Steak Soft Tacos,"[Fresh Tomato Salsa, [Cheese, Lettuce]]",18.50,9.25
4489,1786,4,Chips and Guacamole,NaN,17.80,4.45

In [57]:
## select only the products with quantity equals to 1
chipo_dropped = chipo_dropped[chipo_dropped.quantity == 1]
chipo_dropped

,order_id,quantity,item_name,choice_description,item_price,unity_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
6,3,1,Side of Chips,NaN,1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
10,5,1,Chips and Guacamole,NaN,4.45,4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75,8.75
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49,8.49
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",8.99,8.99
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.99,8.99
28,14,1,Canned Soda,[Dr. Pepper],1.09,1.09
33,17,1,Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",8.99,8.99
34,17,1,Bottled Water,NaN,1.09,1.09
38,18,1,Chips and Tomatillo Green Chili Salsa,NaN,2.95,2.95
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75,11.75
40,19,1,Chips,NaN,2.15,2.15
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75
54,25,1,Steak Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.99,8.99
56,26,1,Barbacoa Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",9.25,9.25
57,26,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
62,28,1,Veggie Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
92,40,1,Steak Crispy Tacos,"[Fresh Tomato Salsa, Sour Cream]",9.25,9.25
111,49,1,Chips and Tomatillo Red Chili Salsa,NaN,2.95,2.95
168,75,1,Barbacoa Crispy Tacos,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",11.75,11.75
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
191,85,1,Chips and Roasted Chili-Corn Salsa,NaN,2.39,2.39
233,102,1,Chips and Roasted Chili Corn Salsa,NaN,2.95,2.95
237,103,1,Carnitas Soft Tacos,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",9.25,9.25
250,109,1,Chicken Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",10.98,10.98
263,114,1,Canned Soft Drink,[Coke],1.25,1.25
298,129,1,6 Pack Soft Drink,[Sprite],6.49,6.49
300,130,1,Chips and Tomatillo-Red Chili Salsa,NaN,2.39,2.39
510,214,1,Burrito,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",7.40,7.40
520,217,1,Crispy Tacos,[Adobo-Marinated and Grilled Steak],7.40,7.40
554,230,1,Carnitas Crispy Tacos,[Roasted Chili Corn Salsa],9.25,9.25
606,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Cheese, Gua...",11.89,11.89
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",8.99,8.99
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",7.40,7.40
674,279,1,Chips and Mild Fresh Tomato Salsa,NaN,3.00,3.00
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
1132,468,1,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.89,11.89
1229,501,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.89,11.89
1414,575,1,Salad,"[Brown Rice, Adobo-Marinated and Grilled Chick...",7.40,7.40
1653,668,1,Veggie Crispy Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49
1694,686,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49,8.49
3750,1500,1,Carnitas Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.99,8.99

In [59]:
# select only the item_name and item_price columns

chipo_dropped = chipo_dropped.loc[:, ["item_name", "item_price"]]
chipo_dropped

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
16                          Chicken Burrito        8.49
21                         Barbacoa Burrito        8.99
27                         Carnitas Burrito        8.99
28                              Canned Soda        1.09
33                            Carnitas Bowl        8.99
34                            Bottled Water        1.09
38    Chips and Tomatillo Green Chili Salsa        2.95
39                            Barbacoa Bowl       11.75
40                                    Chips        2.15
44                       Chicken Salad Bowl        8.75
54                               Steak Bowl        8.99
56                      Barbacoa Soft Tacos        9.25
57                           Veggie Burrito       11.25
62                              Veggie Bowl       11.25
92                       Steak Crispy Tacos        9.25
111     Chips and Tomatillo Red Chili Salsa        2.95
168                   Barbacoa Crispy Tacos       11.75
186                       Veggie Salad Bowl       11.25
191      Chips and Roasted Chili-Corn Salsa        2.39
233      Chips and Roasted Chili Corn Salsa        2.95
237                     Carnitas Soft Tacos        9.25
250                           Chicken Salad       10.98
263                       Canned Soft Drink        1.25
298                       6 Pack Soft Drink        6.49
300     Chips and Tomatillo-Red Chili Salsa        2.39
510                                 Burrito        7.40
520                            Crispy Tacos        7.40
554                   Carnitas Crispy Tacos        9.25
606                        Steak Salad Bowl       11.89
664                             Steak Salad        8.99
673                                    Bowl        7.40
674       Chips and Mild Fresh Tomato Salsa        3.00
738                       Veggie Soft Tacos       11.25
1132                    Carnitas Salad Bowl       11.89
1229                    Barbacoa Salad Bowl       11.89
1414                                  Salad        7.40
1653                    Veggie Crispy Tacos        8.49
1694                           Veggie Salad        8.49
3750                         Carnitas Salad        8.99

In [61]:

# sort the values from the most to less expensive

chipo_dropped=chipo_dropped.sort_values("item_price", ascending=False)
chipo_dropped

                                  item_name  item_price
606                        Steak Salad Bowl       11.89
1229                    Barbacoa Salad Bowl       11.89
1132                    Carnitas Salad Bowl       11.89
7                             Steak Burrito       11.75
168                   Barbacoa Crispy Tacos       11.75
39                            Barbacoa Bowl       11.75
738                       Veggie Soft Tacos       11.25
186                       Veggie Salad Bowl       11.25
62                              Veggie Bowl       11.25
57                           Veggie Burrito       11.25
250                           Chicken Salad       10.98
5                              Chicken Bowl       10.98
8                          Steak Soft Tacos        9.25
554                   Carnitas Crispy Tacos        9.25
237                     Carnitas Soft Tacos        9.25
56                      Barbacoa Soft Tacos        9.25
92                       Steak Crispy Tacos        9.25
664                             Steak Salad        8.99
54                               Steak Bowl        8.99
3750                         Carnitas Salad        8.99
21                         Barbacoa Burrito        8.99
27                         Carnitas Burrito        8.99
33                            Carnitas Bowl        8.99
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
44                       Chicken Salad Bowl        8.75
1653                    Veggie Crispy Tacos        8.49
16                          Chicken Burrito        8.49
1694                           Veggie Salad        8.49
1414                                  Salad        7.40
510                                 Burrito        7.40
520                            Crispy Tacos        7.40
673                                    Bowl        7.40
298                       6 Pack Soft Drink        6.49
10                      Chips and Guacamole        4.45
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
674       Chips and Mild Fresh Tomato Salsa        3.00
111     Chips and Tomatillo Red Chili Salsa        2.95
233      Chips and Roasted Chili Corn Salsa        2.95
38    Chips and Tomatillo Green Chili Salsa        2.95
3     Chips and Tomatillo-Green Chili Salsa        2.39
300     Chips and Tomatillo-Red Chili Salsa        2.39
191      Chips and Roasted Chili-Corn Salsa        2.39
0              Chips and Fresh Tomato Salsa        2.39
40                                    Chips        2.15
6                             Side of Chips        1.69
263                       Canned Soft Drink        1.25
28                              Canned Soda        1.09
34                            Bottled Water        1.09

### Step 6. Sort by the name of the item

In [62]:
chipo.item_name.sort_values()

# OR

chipo.sort_values(by="item_name")

,order_id,quantity,item_name,choice_description,item_price,unity_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [64]:
chipo[chipo.quantity== chipo.quantity.max()]

,order_id,quantity,item_name,choice_description,item_price,unity_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,2.95

In [66]:
chipo[chipo.quantity== chipo.quantity.max()].quantity.values[0]

15

### Step 8. How many times was a Veggie Salad Bowl ordered?

18

In [67]:
chipo

,order_id,quantity,item_name,choice_description,item_price,unity_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

### Step 9. How many times did someone order more than one Canned Soda?

20